# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trun_svd <- function(X, k) {
    .Call(`_eimpute_trun_svd`, X, k)
}

#' @noRd
#' @param omega The matrix index of the observed value
#' @param X The obeserved value of the matrix
#' @param m, n The dimension of the matrix
#' @param rank The rank of matrix
#' @param max_it	 maximum number of iterations.
#' @param tol convergence threshold, measured as the relative change in the Frobenius norm between two successive estimates.
#' @param type computing singular value decomposition, 1 is truncated singular value decomposition, 2 is randomized singular value decomposition
#' @description Use Rcpp to fit a low-rank matrix approximation to a matrix with two method computing singular value decomposition.
kkt_fix <- function(omega, X, m, n, rank, max_it, tol, type) {
    .Call(`_eimpute_kkt_fix`, omega, X, m, n, rank, max_it, tol, type)
}

